version: '2'

services:

  rabbitmq-server:
    image: "lavkesh/rabbitmq-server:${RABBITMQ_IMAGE_VERSION}"
    ports:
      - "5672"
      - "15672"
    environment:
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD_HASH
    networks:
      - my-network

  eureka-server:
    image: "lavkesh/eureka-server:${EUREKA_IMAGE_VERSION}"
    ports:
      - "8080"
    environment:
      - APPLICATION_NAME=eureka-server
      - SPRING_PROFILES_ACTIVE
      - REGISTRY_USERNAME
      - REGISTRY_PASSWORD
    networks:
      - my-network

  config-server:
    image: "lavkesh/config-server:${CONFIG_SERVER_IMAGE_VERSION}"
    ports:
      - "8080"
      - "9080"
    environment:
      - APPLICATION_NAME=config-server
      - SPRING_PROFILES_ACTIVE
      - GIT_CONFIG_URL
      - REGISTRY_USERNAME
      - REGISTRY_PASSWORD
      - CONFIG_LABEL=ELK_stack
    networks:
      - my-network

  test-service-app:
    image: "lavkesh/test-service:${TEST_SERVICE_IMAGE_VERSION}"
    ports:
      - "8080"
      - "9080"
    environment:
      - APPLICATION_NAME=test-service
      - SPRING_PROFILES_ACTIVE
    networks:
      - my-network

  security-service-app:
    image: "lavkesh/security-service:${SECURITY_SERVICE_IMAGE_VERSION}"
    ports:
      - "8080"
      - "9080"
    environment:
      - APPLICATION_NAME=security-service
      - SPRING_PROFILES_ACTIVE
    networks:
      - my-network

  api-gateway-service-app:
    image: "lavkesh/api-gateway-service:${API_GATEWAY_SERVICE_IMAGE_VERSION}"
    ports:
      - "8080"
      - "9080"
    environment:
      - APPLICATION_NAME=api-gateway-service
      - SPRING_PROFILES_ACTIVE
    networks:
      - my-network

networks:
  my-network:
    driver: bridge