version: '2'

services:

  elasticsearch-server:
    image: "elasticsearch:5.5"
    ports:
      - 9200
      - 9300
    environment:  
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - my-network

  kibana-server:
    image: "kibana:5.5"
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch-server:9200
    networks:
      - my-network

  rabbitmq-server:
    image: "lavkesh/rabbitmq-server:${IMAGE_VERSION}"
    ports:
      - "5672"
      - "15672"
    environment:
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD
    networks:
      - my-network

  logtash-server:
    image: "lavkesh/logtash-server:${IMAGE_VERSION}"
    environment:
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD
    networks:
      - my-network

  eureka-server:
    image: "lavkesh/eureka-server:${IMAGE_VERSION}"
    ports:
      - "8080"
    environment:
      - APPLICATION_NAME=eureka-server
      - SPRING_PROFILES_ACTIVE
      - REGISTRY_USERNAME
      - REGISTRY_PASSWORD
    networks:
      - my-network

  config-server:
    image: "lavkesh/config-server:${IMAGE_VERSION}"
    ports:
      - "8080"
      - "9080"
    environment:
      - APPLICATION_NAME=config-server
      - SPRING_PROFILES_ACTIVE
      - GIT_CONFIG_URL
      - REGISTRY_USERNAME
      - REGISTRY_PASSWORD
      - CONFIG_LABEL
    networks:
      - my-network

  test-service-app:
    image: "lavkesh/test-service:${IMAGE_VERSION}"
    ports:
      - "8080"
      - "9080"
    environment:
      - APPLICATION_NAME=test-service
      - SPRING_PROFILES_ACTIVE
    networks:
      - my-network

  security-service-app:
    image: "lavkesh/security-service:${IMAGE_VERSION}"
    ports:
      - "8080"
      - "9080"
    environment:
      - APPLICATION_NAME=security-service
      - SPRING_PROFILES_ACTIVE
    networks:
      - my-network

  api-gateway-service-app:
    image: "lavkesh/api-gateway-service:${IMAGE_VERSION}"
    ports:
      - "8080"
      - "9080"
    environment:
      - APPLICATION_NAME=api-gateway-service
      - SPRING_PROFILES_ACTIVE
    networks:
      - my-network

networks:
  my-network:
    driver: bridge