server:
  port: 8080

# RabbitMQ Configuaration
spring:
  rabbitmq:
    host: rabbitmq-server
    username: '{cipher}aa29e7afa964ff8ca553ba41734fae7856f60dd82e0bbe8750fff7318b051adc'
    password: '{cipher}b3f58fb72b724c23955f29b11d0872aea3b6b1246f63300231adbcbd3dacfb44'

# Management console
management:
  context-path: /manage
  port: 9080

endpoints:
  enabled: false
  sensitive: true
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

# Logging
logging:
  config: classpath:logback.xml
