server:
  port: 8764
  context-path: /security-service

# Management Configuration
management:
  port: 9764
  context-path: /manage

endpoints:
  enabled: true
  sensitive: false

test-service:
  ribbon.listOfServers: http://localhost:8763