server:
  port: 8764

# Disable Eureka server
eureka:
  client:
    enabled: false

# Management Configuration
management:
  port: 9764
  context-path: /manage

endpoints:
  enabled: true
  sensitive: false

test-service:
  ribbon.listOfServers: http://localhost:8763

application:
  username: user
  password: password

lavkesh:
  security:
    enabled: true
    jwt-path-to-skip:
      - '/login'
      - '/logout'
    jwt-authentication-path:
      - '/**'
    ajax-authentication-path:
      - '/login'
    jwt:
      tokenExpirationTime: 5
      refreshTokenExpTime: 10
      tokenIssuer: 'Security Service'
      privateKeyPath: 'privatekey.der'
      publicKeyPath: 'pubkey.der'