# Zuul Proxy settings
zuul:
  strip-prefix: false
  ignored-services: 'config-server'
  routes:
    security-service:
      serviceId: security-service
      path: /security-service/**
      stripPrefix: false
    test-service:
      serviceId: test-service
      path: /test-service/**
      stripPrefix: false

#Security Configuration
lavkesh:
  security:
    enabled: true
    anonymous-path:
      - '/security-service/usernameAndPassword'
      - '/security-service/login'
    publicKeyPath: 'pubkey.der'