server:
  port: 8080
  context-path: /registry

# Eureka Server Settings
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}${server.context-path}/
  server:
    wait-time-in-ms-when-sync-empty: 0

# Spring Security Settings
security:
  basic:
    enabled: true
  user:
    name: ${REGISTRY_USERNAME}
    password: ${REGISTRY_PASSWORD}

logging:
  config: classpath:com/lavkesh/cloud/logback-spring.xml