server:
  port: 8762
  context-path: /config

# Disable eureka for local
eureka:
  client:
    enabled: false

# Management Configuration
management:
  port: 9762
  context-path: /manage

endpoints:
  enabled: true
  sensitive: false