server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://${REGISTRY_USERNAME}:${REGISTRY_PASSWORD}@localhost:8761/registry/eureka/

management:
  port: 9762

endpoints:
  enabled: true
  sensitive: false