# Config server git configuaration
spring:
  cloud:
    bus:
      destination: test-bus
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: ${GIT_CONFIG_URL}
          searchPaths: 'application-config/{profile},application-config/{profile}/{application}'
      name: config-server

# Spring Security Settings
security:
  basic:
    enabled: true
  user:
    name: ${CONFIG_SERVER_USERNAME}
    password: ${CONFIG_SERVER_PASSWORD}

# Encrypt Key For Config
encrypt:
  key: 36E2D4954B9F6EFB2BC397D1D3CBD