server:
  port: 8765
  context-path: /api

# Management Configuration
management:
  port: 9765
  context-path: /manage

endpoints:
  enabled: true
  sensitive: false

# Zuul Proxy settings
zuul:
  strip-prefix: false
  ignored-services: 'config-server'
  routes:
    security-service:
      serviceId: security-service
      path: /security-service/**
      stripPrefix: false
    test-service:
      serviceId: test-service
      path: /test-service/**
      stripPrefix: false