server:
  port: 8765

# Disable Eureka server
eureka:
  client:
    enabled: false

# Management Configuration
management:
  port: 9765
  context-path: /manage

endpoints:
  enabled: true
  sensitive: false

# Zuul Proxy settings
zuul:
  ignored-services: 'config-server'
  sensitive-headers:
  routes:
    security-service:
      path: /security-service/**
      url: http://localhost:8764
      stripPrefix: false
    test-service:
      path: /test-service/**
      url: http://localhost:8763
      stripPrefix: false

authentication:
  jwt-path-to-skip:
    - '${server.context-path}/security-service/login'
    - '${server.context-path}/security-service/logout'
  jwt-authentication-path:
    - '${server.context-path}/**'