server:
  port: 8763

# Eureka Server Settings
eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
    lease-expiration-duration-in-seconds: 60
    hostname: localhost
  client:
    registry-fetch-interval-seconds: 20
    serviceUrl:
      defaultZone: http://${REGISTRY_USERNAME}:${REGISTRY_PASSWORD}@localhost:8761/registry/eureka/

REGISTRY_USERNAME: eureka
REGISTRY_PASSWORD: password

# Management Configuration
management:
  port: 9763
  context-path: /manage

endpoints:
  enabled: true
  sensitive: false

lavkesh:
  application:
    name: test
  security:
    enabled: true
    publicKeyPath: 'pubkey.der'