server:
  port: 8763
  context-path: /test-service

# Disable Eureka server
eureka:
  client:
    enabled: false

# Management Configuration
management:
  port: 9763
  context-path: /manage

endpoints:
  enabled: true
  sensitive: false

lavkesh.application.name: test